name: CI - Engine nightly

on:
  schedule:
    # nightly at 03:00
    - cron: 0 3 * * *

env:
  S3_ACCESS_KEY: ${{ secrets.S3_ACCESS_KEY }}
  S3_SECRET_KEY: ${{ secrets.S3_SECRET_KEY }}
  DM_PACKAGES_URL: ${{ secrets.DM_PACKAGES_URL }}
  DM_ARCHIVE_DOMAIN: ${{ secrets.DM_ARCHIVE_DOMAIN }}
  DM_RELEASE_REPOSITORY: ${{ secrets.DM_RELEASE_REPOSITORY }}


jobs:
  build-engine-macos-64:
    runs-on: macOS-latest
    steps: [
      { name: 'Checkout', uses: actions/checkout@v2 },
      { name: 'Install Python', uses: actions/setup-python@v2, with: { python-version: 3.x, architecture: x64 } },
      { name: 'Install Java', uses: actions/setup-java@v3, with: { java-version: '11.0.15', distribution: 'microsoft'} },
      { name: 'Install dependencies', run: 'ci/ci.sh install' },
      {
        name: 'ASAN',
        run: 'ci/ci.sh --platform=x86_64-macos --with-asan --skip-builtins --skip-docs engine'
      },
      {
        name: 'UBSAN',
        run: 'ci/ci.sh --platform=x86_64-macos --with-ubsan --skip-builtins --skip-docs engine'
      },
      {
         name: 'Notify if build status changed',
         uses: homoluctus/slatify@master,
         if: failure(),
         with: { type: '${{ job.status }}', job_name: '${{ job.status }}', channel: '#defold-alarms-build', url: '${{ secrets.SLACK_WEBHOOK }}',
               mention: 'here', mention_if: 'failure', commit: true, token: '${{ secrets.SERVICES_GITHUB_TOKEN }}' }
      }]

  build-engine-linux-64:
    runs-on: ubuntu-20.04
    steps: [
      { name: 'Checkout', uses: actions/checkout@v2 },
      { name: 'Install Python', uses: actions/setup-python@v2, with: { python-version: 3.x, architecture: x64 } },
      { name: 'Install Java', uses: actions/setup-java@v3, with: { java-version: '11.0.15', distribution: 'microsoft'} },
      { name: 'Install dependencies', run: 'ci/ci.sh install' },
      {
        name: 'ASAN',
        run: 'ci/ci.sh --platform=x86_64-linux --with-asan --skip-builtins --skip-docs engine'
      },
      {
        name: 'UBSAN',
        run: 'ci/ci.sh --platform=x86_64-linux --with-ubsan --skip-builtins --skip-docs engine'
      },
      {
        name: 'VALGRIND',
        run: 'ci/ci.sh --platform=x86_64-linux --with-valgrind --skip-builtins --skip-docs engine'
      },
      {
         name: 'Notify if build status changed',
         uses: homoluctus/slatify@master,
         if: failure(),
         with: { type: '${{ job.status }}', job_name: '${{ job.status }}', channel: '#defold-alarms-build', url: '${{ secrets.SLACK_WEBHOOK }}',
               mention: 'here', mention_if: 'failure', commit: true, token: '${{ secrets.SERVICES_GITHUB_TOKEN }}' }
      }]
